"""empty message

Revision ID: 03af7da6b66c
Revises: a10f28451302
Create Date: 2024-02-28 19:54:38.911671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03af7da6b66c'
down_revision = 'a10f28451302'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_invest_record',
    sa.Column('pId', sa.BIGINT(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('pProductId', sa.BIGINT(), nullable=True, comment='产品id'),
    sa.Column('pUid', sa.BIGINT(), nullable=True, comment='用户id'),
    sa.Column('pSerialNo', sa.String(length=64), nullable=True, comment='投资编号'),
    sa.Column('pBeginDate', sa.DateTime(), nullable=True, comment='加入日期'),
    sa.Column('pEndDate', sa.DateTime(), nullable=True, comment='到期日期'),
    sa.Column('pRedeemDate', sa.DateTime(), nullable=True, comment='赎回日期'),
    sa.Column('pMatchDate', sa.DateTime(), nullable=True, comment='匹配日期'),
    sa.Column('pAmount', sa.Float(precision=8, asdecimal=2), nullable=True, comment='金额'),
    sa.Column('pDate', sa.DateTime(), nullable=True, comment='系统时间'),
    sa.Column('pEarningsType', sa.String(length=100), nullable=True, comment='产品编号'),
    sa.Column('pProductType', sa.Integer(), nullable=True, comment='收益率类型'),
    sa.Column('pEarnings', sa.Float(precision=4, asdecimal=2), nullable=True, comment='收益率'),
    sa.Column('pAdvanceRedemption', sa.Float(precision=4, asdecimal=2), nullable=True, comment='提前赎回利率'),
    sa.Column('pDeadline', sa.Integer(), nullable=True, comment='选择期限'),
    sa.Column('aCurrentPeriod', sa.Integer(), nullable=True, comment='当前期（账户资金日志表）'),
    sa.Column('pProspectiveEarnings', sa.Float(precision=8, asdecimal=2), nullable=True, comment='预期收益'),
    sa.Column('pExpectedAnnualIncome', sa.Float(precision=4, asdecimal=2), nullable=True, comment='预期年化收益'),
    sa.Column('pMonthInterest', sa.Float(precision=8, asdecimal=2), nullable=True, comment='每月盈取利息'),
    sa.Column('pMonthlyExtractInterest', sa.Float(precision=8, asdecimal=2), nullable=True, comment='每月提取利息'),
    sa.Column('pInterestStartDate', sa.DateTime(), nullable=True, comment='开始计息时间'),
    sa.Column('pInterestEndDate', sa.Integer(), nullable=True, comment='结束计息时间'),
    sa.Column('pEarningsIsFinished', sa.Float(precision=10, asdecimal=2), nullable=True, comment='收益是否完成'),
    sa.Column('pAvailableBalance', sa.Float(precision=10, asdecimal=2), nullable=True, comment='可用余额'),
    sa.Column('pFrozenMoney', sa.Float(precision=10, asdecimal=2), nullable=True, comment='冻结金额'),
    sa.Column('pSystemPaymentDate', sa.Integer(), nullable=True, comment='每月回款日'),
    sa.Column('pCurrentMonth', sa.Integer(), nullable=True, comment='当前期（用户购买产品记录表）'),
    sa.Column('pDeductInterest', sa.Float(precision=8, asdecimal=2), nullable=True, comment='扣去利息'),
    sa.Column('pNotInvestMoney', sa.Float(precision=10, asdecimal=2), nullable=True, comment='未投资金额'),
    sa.Column('pStatus', sa.Integer(), nullable=True, comment='状态'),
    sa.Column('pEndInvestTotalMoney', sa.Float(precision=8, asdecimal=2), nullable=True, comment='到期应回总本息'),
    sa.Column('pCurrentRealTotalMoney', sa.Float(precision=8, asdecimal=2), nullable=True, comment='当前期实回总本息'),
    sa.Column('pDeadlineCount', sa.Float(precision=8, asdecimal=2), nullable=True, comment='统计'),
    sa.Column('pProductName', sa.String(length=32), nullable=True, comment='产品名称'),
    sa.Column('pMonthlyDeposit', sa.Float(precision=8, asdecimal=2), nullable=True, comment='月存'),
    sa.Column('pMonthlyDepositCount', sa.Integer(), nullable=True, comment='月存笔数'),
    sa.Column('pTakeMonth', sa.Float(precision=8, asdecimal=2), nullable=True, comment='月乘'),
    sa.Column('pTakeMonthCount', sa.Integer(), nullable=True, comment='月乘笔数'),
    sa.Column('pMayTake', sa.Float(precision=8, asdecimal=2), nullable=True, comment='月取'),
    sa.Column('pMayTakeCount', sa.Integer(), nullable=True, comment='月取笔数'),
    sa.Column('pTotalAsDay', sa.Integer(), nullable=True, comment='总天数'),
    sa.Column('pDeadlineAsDay', sa.Integer(), nullable=True, comment='投资天数'),
    sa.Column('pDays', sa.Integer(), nullable=True, comment='天数'),
    sa.Column('pDeadlines', sa.DateTime(), nullable=True, comment='投资期限'),
    sa.Column('username', sa.String(length=64), nullable=True, comment='投资用户名'),
    sa.Column('pEarnedInterest', sa.Float(precision=8, asdecimal=2), nullable=True, comment='已赚取利息'),
    sa.Column('pRemark', sa.String(length=64), nullable=True, comment='备注'),
    sa.Column('sumAvailableBalanceAndFrozenMoney', sa.Float(precision=8, asdecimal=2), nullable=True, comment='SUM(可用余额+冻结金额)'),
    sa.Column('pTotal', sa.Float(precision=8, asdecimal=2), nullable=True, comment='总计'),
    sa.ForeignKeyConstraint(['pProductId'], ['t_product.proId'], ),
    sa.ForeignKeyConstraint(['pUid'], ['t_user.id'], ),
    sa.PrimaryKeyConstraint('pId')
    )
    op.create_table('t_deal_log',
    sa.Column('aId', sa.BIGINT(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('aUserId', sa.BIGINT(), nullable=True, comment='用户id'),
    sa.Column('pId', sa.BIGINT(), nullable=True, comment='投资记录主键'),
    sa.Column('aCurrentPeriod', sa.Integer(), nullable=True, comment='当前期'),
    sa.Column('aReceiveOrPay', sa.Float(precision=8, asdecimal=2), nullable=True, comment='收付，1收2付'),
    sa.Column('aTransferSerialNo', sa.String(length=128), nullable=True, comment='交易流水号'),
    sa.Column('aDate', sa.DateTime(), nullable=True, comment='交易时间'),
    sa.Column('aType', sa.Integer(), nullable=True, comment='交易类型'),
    sa.Column('aTransferStatus', sa.Integer(), nullable=True, comment='交易状态，0失败1成功'),
    sa.Column('aBeforeTradingMoney', sa.Float(precision=8, asdecimal=2), nullable=True, comment='交易前金额'),
    sa.Column('aAmount', sa.Float(precision=8, asdecimal=2), nullable=True, comment='金额'),
    sa.Column('aAfterTradingMoney', sa.Float(precision=8, asdecimal=2), nullable=True, comment='交易后金额'),
    sa.Column('aDescreption', sa.String(length=128), nullable=True, comment='交易详情'),
    sa.ForeignKeyConstraint(['aUserId'], ['t_user.id'], ),
    sa.ForeignKeyConstraint(['pId'], ['t_invest_record.pId'], ),
    sa.PrimaryKeyConstraint('aId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_deal_log')
    op.drop_table('t_invest_record')
    # ### end Alembic commands ###
