"""empty message

Revision ID: 21b2af55db9b
Revises: 
Create Date: 2024-03-08 16:31:24.224618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21b2af55db9b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_loan',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('loanNum', sa.Float(precision=8, asdecimal=2), nullable=True, comment='借款金额'),
    sa.Column('lUid', sa.BIGINT(), nullable=True, comment='用户id'),
    sa.Column('duration', sa.Integer(), nullable=True, comment='借款时长'),
    sa.Column('lName', sa.String(length=64), nullable=True, comment='借款人姓名'),
    sa.Column('lRepayType', sa.Integer(), nullable=True, comment='还款模式'),
    sa.Column('lRate', sa.Float(precision=4, asdecimal=2), nullable=True, comment='借款利率'),
    sa.Column('lRepayDay', sa.Integer(), nullable=True, comment='还款日'),
    sa.Column('status', sa.Integer(), nullable=True, comment='审批状态'),
    sa.Column('applyDate', sa.DateTime(), nullable=True, comment='申请时间'),
    sa.ForeignKeyConstraint(['lUid'], ['t_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_debt_info',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('debtNo', sa.String(length=128), nullable=True, comment='债权编号'),
    sa.Column('loanNo', sa.BIGINT(), nullable=True, comment='借款id'),
    sa.Column('debtorsName', sa.String(length=64), nullable=True, comment='债务人名称'),
    sa.Column('debtorsId', sa.String(length=128), nullable=True, comment='债务人身份证号'),
    sa.Column('loanPurpose', sa.String(length=128), nullable=True, comment='借款用途'),
    sa.Column('loanType', sa.Integer(), nullable=True, comment='借款类型'),
    sa.Column('loanStartDate', sa.DateTime(), nullable=True, comment='原始借款开始日期'),
    sa.Column('loanPeriod', sa.Integer(), nullable=True, comment='原始借款期限'),
    sa.Column('loanEndDate', sa.Date(), nullable=True, comment='原始借款到期日期'),
    sa.Column('repaymentStyle', sa.Integer(), nullable=True, comment='还款方式'),
    sa.Column('repaymenDate', sa.Integer(), nullable=True, comment='还款日'),
    sa.Column('repaymenMoney', sa.Float(precision=8, asdecimal=2), nullable=True, comment='还款金额'),
    sa.Column('debtMoney', sa.Float(precision=8, asdecimal=2), nullable=True, comment='债权金额'),
    sa.Column('debtYearRate', sa.Float(precision=4, asdecimal=2), nullable=True, comment='债权年化利率'),
    sa.Column('debtMonthRate', sa.Float(precision=4, asdecimal=2), nullable=True, comment='债权月利率'),
    sa.Column('debtTransferredMoney', sa.Float(precision=8, asdecimal=2), nullable=True, comment='债权转入金额'),
    sa.Column('debtTransferredDate', sa.Date(), nullable=True, comment='债权转入日期'),
    sa.Column('debtTransferredPeriod', sa.Date(), nullable=True, comment='债权转入期限'),
    sa.Column('debtRansferOutDate', sa.Date(), nullable=True, comment='债权转出日期'),
    sa.Column('creditor', sa.String(length=64), nullable=True, comment='债权人'),
    sa.Column('debtStatus', sa.Integer(), nullable=True, comment='债权状态'),
    sa.Column('borrowerId', sa.BIGINT(), nullable=True, comment='借款人ID'),
    sa.Column('availablePeriod', sa.Integer(), nullable=True, comment='可用金额'),
    sa.Column('matchedMoney', sa.Float(precision=8, asdecimal=2), nullable=True, comment='已匹配金额'),
    sa.Column('matchedStatus', sa.Integer(), nullable=True, comment='匹配状态'),
    sa.Column('repaymentStyleName', sa.String(length=64), nullable=True, comment='还款方式名称'),
    sa.Column('debtStatusName', sa.String(length=64), nullable=True, comment='债权状态名字'),
    sa.Column('matchedStatusName', sa.String(length=64), nullable=True, comment='匹配状态名称'),
    sa.Column('debtType', sa.Integer(), nullable=True, comment='标的类型'),
    sa.Column('debtTypeName', sa.String(length=64), nullable=True, comment='标的类型名称'),
    sa.ForeignKeyConstraint(['borrowerId'], ['t_user.id'], ),
    sa.ForeignKeyConstraint(['loanNo'], ['t_loan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_debtor_record',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('claimsId', sa.BIGINT(), nullable=True, comment='债权id'),
    sa.Column('receivableDate', sa.DateTime(), nullable=True, comment='应还日期'),
    sa.Column('receivableMoney', sa.Float(precision=8, asdecimal=2), nullable=True, comment='应还余额'),
    sa.Column('currentTerm', sa.Integer(), nullable=True, comment='当前还款期'),
    sa.Column('recordDate', sa.DateTime(), nullable=True, comment='记录日期'),
    sa.Column('isReturned', sa.Integer(), nullable=True, comment='是否还款'),
    sa.ForeignKeyConstraint(['claimsId'], ['t_debt_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_debtor_record')
    op.drop_table('t_debt_info')
    op.drop_table('t_loan')
    # ### end Alembic commands ###
