"""empty message

Revision ID: 839d0e3a5f46
Revises: 9b258d82c9e1
Create Date: 2024-02-15 14:23:02.032291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '839d0e3a5f46'
down_revision = '9b258d82c9e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_user',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True, comment='用户名'),
    sa.Column('password', sa.String(length=128), nullable=True, comment='密码'),
    sa.Column('payPassword', sa.String(length=128), nullable=True, comment='支付密码'),
    sa.Column('payPwdStatus', sa.Integer(), nullable=True, comment='支付密码验证'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='邮箱'),
    sa.Column('emailStatus', sa.Integer(), nullable=True, comment='邮箱验证'),
    sa.Column('inviteId', sa.Integer(), nullable=True, comment='邀请码'),
    sa.Column('ip', sa.String(length=128), nullable=True, comment='ip'),
    sa.Column('phone', sa.String(length=11), nullable=True, comment='手机号'),
    sa.Column('onlock', sa.Integer(), nullable=True, comment='用户状态'),
    sa.Column('phoneStatus', sa.Integer(), nullable=True, comment='手机验证'),
    sa.Column('realName', sa.String(length=64), nullable=True, comment='真实姓名'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='备注'),
    sa.Column('realNameStatus', sa.Integer(), nullable=True, comment='实名认证'),
    sa.Column('nick_name', sa.String(length=200), nullable=True, comment='昵称'),
    sa.Column('avatar', sa.String(length=128), nullable=True, comment='头像'),
    sa.Column('idNum', sa.String(length=64), nullable=True, comment='身份证号码'),
    sa.Column('sumFriends', sa.Integer(), nullable=True, comment='邀请数量统计'),
    sa.Column('invite_user_id', sa.Integer(), nullable=True, comment='邀请的用户的ID'),
    sa.Column('role', sa.Integer(), nullable=True, comment='是否管理员'),
    sa.Column('loginTime', sa.DateTime(), nullable=True, comment='登录时间'),
    sa.Column('registerTime', sa.DateTime(), nullable=True, comment='用户注册的时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_account',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userId', sa.BIGINT(), nullable=True, comment='用户表主键'),
    sa.Column('total', sa.Float(precision=10, asdecimal=2), nullable=True, comment='帐户总额'),
    sa.Column('balance', sa.Float(precision=10, asdecimal=2), nullable=True, comment='帐户可余额'),
    sa.Column('frozen', sa.Float(precision=10, asdecimal=2), nullable=True, comment='账户总计冻结总额'),
    sa.Column('inverstmentW', sa.Float(precision=10, asdecimal=2), nullable=True, comment='总计待收本金'),
    sa.Column('interestTotal', sa.Float(precision=10, asdecimal=2), nullable=True, comment='总计待收利息'),
    sa.Column('addCapitalTotal', sa.Float(precision=10, asdecimal=2), nullable=True, comment='月投总额'),
    sa.Column('recyclingInterest', sa.Float(precision=10, asdecimal=2), nullable=True, comment='月取总额'),
    sa.Column('capitalTotal', sa.Float(precision=10, asdecimal=2), nullable=True, comment='月乘总额'),
    sa.Column('inverstmentA', sa.Float(precision=10, asdecimal=2), nullable=True, comment='已投资总额'),
    sa.Column('interestA', sa.Float(precision=10, asdecimal=2), nullable=True, comment='已赚取利息'),
    sa.Column('uApplyExtractMoney', sa.Float(precision=10, asdecimal=2), nullable=True, comment='申请提现金额'),
    sa.Column('discount', sa.Float(precision=8, asdecimal=2), nullable=True, comment='代金券的总金额'),
    sa.ForeignKeyConstraint(['userId'], ['t_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_account')
    op.drop_table('t_user')
    # ### end Alembic commands ###
