"""empty message

Revision ID: a10f28451302
Revises: ddab2ea0678b
Create Date: 2024-02-23 17:11:14.278509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a10f28451302'
down_revision = 'ddab2ea0678b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_product',
    sa.Column('proId', sa.BIGINT(), autoincrement=True, nullable=False, comment='产品id'),
    sa.Column('productName', sa.String(length=100), nullable=True, comment='产品名称'),
    sa.Column('closedPeriod', sa.BIGINT(), nullable=True, comment='转让封闭期'),
    sa.Column('earlyRedeptionType', sa.Integer(), nullable=True, comment='提前赎回类型'),
    sa.Column('earningType', sa.Integer(), nullable=True, comment='收益利率类型'),
    sa.Column('investRule', sa.Integer(), nullable=True, comment='数量规则'),
    sa.Column('isAllowTransfer', sa.Integer(), nullable=True, comment='是否可转让'),
    sa.Column('isRepeatInvest', sa.Integer(), nullable=True, comment='是否复投'),
    sa.Column('lowerTimeLimit', sa.Integer(), nullable=True, comment='产品最低期限'),
    sa.Column('proLowerInvest', sa.BIGINT(), nullable=True, comment='产品起投金额'),
    sa.Column('proNum', sa.String(length=100), nullable=True, comment='产品编号'),
    sa.Column('proUpperInvest', sa.BIGINT(), nullable=True, comment='产品投资上限'),
    sa.Column('proTypeId', sa.Integer(), nullable=True, comment='产品投资上限'),
    sa.Column('status', sa.Integer(), nullable=True, comment='状态'),
    sa.Column('upperTimeLimit', sa.Integer(), nullable=True, comment='产品最大期限'),
    sa.Column('wayToReturnMoney', sa.Integer(), nullable=True, comment='回款方式'),
    sa.PrimaryKeyConstraint('proId')
    )
    op.create_table('t_bankcard',
    sa.Column('bankInfoId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bankCardNum', sa.String(length=64), nullable=True, comment='银行卡号'),
    sa.Column('openingBank', sa.String(length=64), nullable=True, comment='开户银行'),
    sa.Column('cityId', sa.Integer(), nullable=True, comment='城市id'),
    sa.Column('userId', sa.BIGINT(), nullable=True, comment='用户表主键'),
    sa.Column('bankId', sa.Integer(), nullable=True, comment='银行编号'),
    sa.Column('bankBranch', sa.String(length=64), nullable=True, comment='银行支行'),
    sa.Column('reservePhone', sa.String(length=64), nullable=True, comment='绑定手机号码'),
    sa.ForeignKeyConstraint(['userId'], ['t_user.id'], ),
    sa.PrimaryKeyConstraint('bankInfoId')
    )
    op.create_table('t_product_rate',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False, comment='编号'),
    sa.Column('incomeRate', sa.Float(precision=4, asdecimal=2), nullable=True, comment='利率值'),
    sa.Column('month', sa.Integer(), nullable=True, comment='月份'),
    sa.Column('productId', sa.BIGINT(), nullable=True, comment='产品编号'),
    sa.ForeignKeyConstraint(['productId'], ['t_product.proId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_product_rate')
    op.drop_table('t_bankcard')
    op.drop_table('t_product')
    # ### end Alembic commands ###
