"""empty message

Revision ID: ddab2ea0678b
Revises: 023a90bf3afb
Create Date: 2024-02-21 20:45:58.574593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddab2ea0678b'
down_revision = '023a90bf3afb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_letter_detail',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.String(length=256), nullable=True),
    sa.Column('pDate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_letter',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('sendID', sa.String(length=64), nullable=True),
    sa.Column('recID', sa.BIGINT(), nullable=True),
    sa.Column('detail_id', sa.BIGINT(), nullable=True),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['detail_id'], ['t_letter_detail.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_letter')
    op.drop_table('t_letter_detail')
    # ### end Alembic commands ###
