"""empty message

Revision ID: f453f938faaa
Revises: a8876167c725
Create Date: 2024-03-09 22:47:44.005605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f453f938faaa'
down_revision = 'a8876167c725'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_funding_not_matched',
    sa.Column('fId', sa.BIGINT(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('fInvestRecordId', sa.BIGINT(), nullable=True, comment='投资记录'),
    sa.Column('fNotMatchedMoney', sa.Float(precision=8, asdecimal=2), nullable=True, comment='待匹配金额'),
    sa.Column('fFoundingType', sa.Integer(), nullable=True, comment='资金类型'),
    sa.Column('fFoundingWeight', sa.Float(precision=8, asdecimal=2), nullable=True, comment='资金'),
    sa.Column('matchedStatus', sa.Integer(), nullable=True, comment='匹配状态'),
    sa.Column('fCreateDate', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['fInvestRecordId'], ['t_invest_record.pId'], ),
    sa.PrimaryKeyConstraint('fId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_funding_not_matched')
    # ### end Alembic commands ###
